apiVersion: skaffold/v4beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  googleCloudBuild:
    projectId: ticketing-dev-413816
  artifacts:
    - image: us.gcr.io/ticketing-dev-413816/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
